osx_image: xcode7.1
cache: cocoapods
podfile: Tests/Podfile
before_install: gem install xcpretty cocoapods obcd slather -N
script: xcodebuild -workspace Tests/Tests.xcworkspace -scheme Tests -sdk iphonesimulator build test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean test | xcpretty -c && exit ${PIPESTATUS[0]}
after_success: slather
